name: Build gbc for arm64 architecture

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Build
        run: GOOS=android GOARCH=arm64 CGO_ENABLED=0 go build -o bin/gbc main.go

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.BUILD_BUNDLE_TOKEN }}"
          prerelease: false
          files: |
            bin/gbc
